Opetushallitus/jod-yksilo

- src/main/java/fi/okm/jod/yksilo/config/AwsCloudFrontRequestIdFilter.java
- src/main/java/fi/okm/jod/yksilo/controller/PingController.java
- src/main/resources/application-cloud.yml
Adds CloudFront request id to logs, making it possible to correate logs with CF access logs which include the client IP.
https://jira.eduuni.fi/browse/OPHJOD-264
> OPHJOD-264: Correlate application logs with CF access logs

- build.gradle
- src/main/java/fi/okm/jod/yksilo/controller/profiili/KoulutusController.java
- src/main/java/fi/okm/jod/yksilo/dto/profiili/KoulutusKategoriaDto.java
- src/main/java/fi/okm/jod/yksilo/repository/KoulutusKategoriaRepository.java
- src/main/java/fi/okm/jod/yksilo/service/profiili/KoulutusService.java
- src/main/java/fi/okm/jod/yksilo/service/profiili/Mapper.java
- src/test/java/fi/okm/jod/yksilo/service/KoulutusServiceTest.java
- src/test/java/fi/okm/jod/yksilo/testutil/LocalizedStrings.java
- src/test/resources/data/create/kategoria-test-data.sql
- src/test/resources/data/create/koulutus-test-data.sql
- src/test/resources/data/delete/kategoria-test-data.sql
- src/test/resources/data/delete/koulutus-test-data.sql
API:n ajateltu käyttö (muutosten jälkeen):
GET /api/profiili/koulutukset palauttaa tarvittavat tiedot koulutusten yleisnäkymään
POST /api/profiili/koulutukset toimii uuden koulutuksen (tai kokonaisen uuden kategorian) lisäämiseen.
Siirryttäessä muokkaukseen yleisnäkymästä ei välttämättä tarvitse ladata tietoja uudelleen koska (1) palauttaa samat tiedot. Tähän voi kuitenkin käyttää GET /api/profiili/kategoria/id tai GET /api/profiili/koulutukset/{id} (koulutuksille joilla ei ole kategoriaa) API:a
Kun tunnistetaan koulutuksen osaamisia, GET /api/profiili/koulutukset/id palauttaa yksittäisen koulutuksen osaamiset lisätietoineen (nimi, kuvaus). Näitä ei tule koulutuksen mukana GET /api/profiili/koulutukset -rajapinnasta.
Tallennus:
kategorian muokkaukseen PATCH /api/profiili/kategoria/id …
> OPHJOD-486: Koulutus apin refaktorointi

- build.gradle
- src/main/java/fi/okm/jod/yksilo/controller/ehdotus/OsaamisetEhdotusController.java
- src/main/java/fi/okm/jod/yksilo/controller/profiili/KoulutusController.java
- src/main/java/fi/okm/jod/yksilo/controller/profiili/KoulutusKokonaisuusController.java
- src/main/java/fi/okm/jod/yksilo/controller/profiili/YksilonOsaaminenController.java
- src/main/java/fi/okm/jod/yksilo/domain/LocalizedString.java
- src/main/java/fi/okm/jod/yksilo/dto/YksiloCsrfDto.java
- src/main/java/fi/okm/jod/yksilo/entity/Koulutus.java
- src/main/java/fi/okm/jod/yksilo/entity/KoulutusKategoria.java
- src/main/java/fi/okm/jod/yksilo/errorhandler/ExceptionHandlerAdvice.java
- src/main/java/fi/okm/jod/yksilo/service/ehdotus/OsaamisetEhdotusService.java
- src/main/java/fi/okm/jod/yksilo/service/profiili/KoulutusService.java
- src/main/java/fi/okm/jod/yksilo/service/profiili/TyopaikkaService.java
- src/main/resources/data-import.sql
- src/main/resources/data.sql
- src/test/java/fi/okm/jod/yksilo/service/KoulutusServiceTest.java
- src/test/java/fi/okm/jod/yksilo/service/TyopaikkaServiceTest.java
- src/test/java/fi/okm/jod/yksilo/testutil/LocalizedStrings.java
A first step in refactoring the profiili API. Adds missing operations to Koulutus and Tyopaikka. Update now suppors adding new Toimenkuva/Koulutus, and removes Toimenkuva/Koulutus if necessary.
see also https://github.com/Opetushallitus/jod-yksilo-ui/pull/92
https://jira.eduuni.fi/browse/OPHJOD-538
> OPHJOD-538: Refactor profiili API (part 1)

- .github/workflows/build.yml
- build.gradle
- src/main/java/fi/okm/jod/yksilo/config/mapping/LocalizedStringMixin.java
- src/main/java/fi/okm/jod/yksilo/config/mapping/MappingConfig.java
- src/main/java/fi/okm/jod/yksilo/domain/LocalizedString.java
- src/main/java/fi/okm/jod/yksilo/dto/profiili/KategoriaDto.java
- src/main/java/fi/okm/jod/yksilo/dto/profiili/KoulutusDto.java
- src/main/java/fi/okm/jod/yksilo/entity/Koulutus.java
- src/main/java/fi/okm/jod/yksilo/entity/KoulutusKategoria.java
- src/main/java/fi/okm/jod/yksilo/entity/Osaaminen.java
- src/main/java/fi/okm/jod/yksilo/entity/Patevyys.java
- src/main/java/fi/okm/jod/yksilo/entity/Toimenkuva.java
- src/main/java/fi/okm/jod/yksilo/entity/Toiminto.java
- src/main/java/fi/okm/jod/yksilo/entity/Tyomahdollisuus.java
- src/main/java/fi/okm/jod/yksilo/entity/Tyopaikka.java
- src/test/java/fi/okm/jod/yksilo/domain/LocalizedStringTest.java
API should not return properties with null value since the API contract generally prohibits null. 
https://jira.eduuni.fi/browse/OPHJOD-580
> OPHJOD-580: Fix API returns null properties

- src/main/java/fi/okm/jod/yksilo/config/mocklogin/MockJodUserImpl.java
- src/main/java/fi/okm/jod/yksilo/config/mocklogin/MockLoginConfig.java
- src/main/java/fi/okm/jod/yksilo/config/mocklogin/MockLoginController.java
- src/main/java/fi/okm/jod/yksilo/config/suomifi/LoginController.java
- src/test/java/fi/okm/jod/yksilo/controller/YksiloControllerTest.java
Fix mock login by replacing the default login page with a custom one (default login page can not be configured to accept query parameters).
https://jira.eduuni.fi/browse/OPHJOD-212
> OPHJOD-212: Fix mock login

- build.gradle
- src/main/java/fi/okm/jod/yksilo/Application.java
- src/main/java/fi/okm/jod/yksilo/controller/TyomahdollisuusController.java
- src/main/java/fi/okm/jod/yksilo/controller/ehdotus/TyomahdollisuudetController.java
- src/main/java/fi/okm/jod/yksilo/entity/Tyomahdollisuus.java
- src/main/java/fi/okm/jod/yksilo/entity/projection/TyomahdollisuusMetadata.java
- src/main/java/fi/okm/jod/yksilo/repository/TyomahdollisuusRepository.java
- src/main/java/fi/okm/jod/yksilo/service/TyomahdollisuusService.java
- src/main/resources/application.yml
- src/main/resources/data-import.sql
- src/test/java/fi/okm/jod/yksilo/controller/TyomahdollisuusControllerTest.java
Changed /api/ehdotus/tyomahdollisuudet to return list of all työmahdollisuus ehdotukset meta data with reference to työmahdollisuus. 
Added /api/tyomahdollisuudet/etsi-id endpoint with query parameter ids which can be used to request list of työmahdolliuudet.
https://jira.eduuni.fi/browse/OPHJOD-646
> OPHJOD-646: Change ehdotus and tyomahdollisuus api

- src/main/java/fi/okm/jod/yksilo/config/SessionConfig.java
- src/main/resources/application.yml
Use redis http session auto-configuration to pick up common properties.
https://jira.eduuni.fi/browse/OPHJOD-717
> OPHJOD-717: Fix session.timeout was ignored

- src/main/java/fi/okm/jod/yksilo/controller/ehdotus/TyomahdollisuudetController.java
- src/main/java/fi/okm/jod/yksilo/entity/Tyomahdollisuus.java
- src/main/java/fi/okm/jod/yksilo/entity/projection/TyomahdollisuusMetadata.java
- src/main/java/fi/okm/jod/yksilo/repository/TyomahdollisuusRepository.java
- src/main/java/fi/okm/jod/yksilo/service/TyomahdollisuusService.java
This PR changes the id type of the työmahdollisuus from varchar to uuid. And starts using the mapping by the ID instead of the title of työmahdollisuus 
https://jira.eduuni.fi/browse/OPHJOD-698
This PR can't be merged before the following changes have been deployed:
https://jira.eduuni.fi/browse/OPHJOD-682 
https://jira.eduuni.fi/browse/OPHJOD-714
And needs to be merged with realated infra changes PR: https://github.com/Opetushallitus/jod-yksilo-infra/pull/41
Update tyomahdollisuudet data from S3 and manually alter tyomahdollisuus.json_id from varchar to uuid.
> OPHJOD-698: Change tyomahdollisuus cluster id from string to uuid

- src/main/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetController.java
Metadata type changed to not null. Since each opportunity must have a fixed type it is logical, that type can't be null.
https://jira.eduuni.fi/browse/OPHJOD-862
> OPHJOD-862: Fix EhdotusMetadata tyyppi to not null in dto schema

- src/main/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetController.java
- src/test/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetControllerTest.java
Inference endpoint response changed to match with type enumeration of 
TYOMAHDOLLISUUS and KOULUTUSMAHDOLLISUUS values
https://jira.eduuni.fi/browse/OPHJOD-906
This PR: should be merged at the same time when kohtaanto service is updated with PR: https://github.com/Opetushallitus/jod-yksilo-kohtaanto/pull/65
> OPHJOD-906: Update inference response

- src/main/java/fi/okm/jod/yksilo/controller/ehdotus/OsaamisetEhdotusController.java
Validate competence matching API only for max 10000 chars. And alllow non-printable chars as newline, tabs, etc.
https://jira.eduuni.fi/browse/OPHJOD-1043
> OPHJOD-1043: Allow non-printable characters for competence matcher

- src/main/java/fi/okm/jod/yksilo/config/mapping/StringToKieliConverter.java
- src/main/java/fi/okm/jod/yksilo/config/mapping/StringToSortDirectionConverter.java
- src/main/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetController.java
- src/main/java/fi/okm/jod/yksilo/service/KoulutusmahdollisuusService.java
- src/main/java/fi/okm/jod/yksilo/service/TyomahdollisuusService.java
- src/main/java/fi/okm/jod/yksilo/service/ehdotus/MahdollisuudetService.java
- src/test/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetControllerTest.java
Added sort property and Content-Language header support to /api/ehdotus/mahdollisuudet.
This change allows frontend to sort combined opportunities alphabetically by user selected language.
https://jira.eduuni.fi/browse/OPHJOD-1133
> OPHJOD-1133: Add lexicalIndex to opportunity metadata

- src/main/java/fi/okm/jod/yksilo/config/koski/KoskiSecurityConfig.java
- src/main/java/fi/okm/jod/yksilo/controller/koski/KoskiOAuth2Controller.java
- src/test/java/fi/okm/jod/yksilo/controller/koski/KoskiOAuth2ControllerTest.java
This update ensures that the user's selected language (locale) is included in OAuth2 authorization requests, so that Koski can show correct language for the user.
https://jira.eduuni.fi/browse/OPHJOD-1329
> OPHJOD-1329: Pass client's user's language to Koski OAuth2

- src/main/java/fi/okm/jod/yksilo/config/koski/KoskiRestClientConfig.java
- src/main/java/fi/okm/jod/yksilo/controller/koski/IntegraatioKoskiController.java
- src/main/java/fi/okm/jod/yksilo/controller/koski/KoskiOAuth2Controller.java
- src/main/java/fi/okm/jod/yksilo/service/koski/KoskiService.java
- src/test/java/fi/okm/jod/yksilo/controller/koski/IntegraatioKoskiControllerTest.java
- src/test/java/fi/okm/jod/yksilo/service/koski/KoskiServiceTest.java
This pull request improves education's import description provided to client and robustness in the system:
- Refactored `KoskiService` to manage and merge localized descriptions effectively using a new `getLocalizedKuvaus` helper method that have default fallback language to Finnish if text is missing. E.g. previously "Avoimen opinnot", now have more detail info: "Avoimen opinnot: Aducate/A1999/Avoin yo, kasv./Kasvatustiede/Kasvat. appr"
- Increased HTTP client timeout values in `KoskiRestClientConfig` to better handle slower API responses and reduce timeout errors.
- Removed unused code.
https://jira.eduuni.fi/browse/OPHJOD-1357
> OPHJOD-1357: Improve education description get from Koski import  

- scripts/update-local-env-data.sh
- src/main/java/fi/okm/jod/yksilo/dto/KoulutusmahdollisuusDto.java
- src/main/java/fi/okm/jod/yksilo/dto/TyomahdollisuusDto.java
- src/main/java/fi/okm/jod/yksilo/entity/koulutusmahdollisuus/Koulutusmahdollisuus.java
- src/main/java/fi/okm/jod/yksilo/entity/koulutusmahdollisuus/KoulutusmahdollisuusJakauma.java
- src/main/java/fi/okm/jod/yksilo/entity/tyomahdollisuus/Tyomahdollisuus.java
- src/main/java/fi/okm/jod/yksilo/entity/tyomahdollisuus/TyomahdollisuusJakauma.java
- src/main/java/fi/okm/jod/yksilo/service/KoulutusmahdollisuusService.java
- src/main/java/fi/okm/jod/yksilo/service/TyomahdollisuusService.java
- src/main/java/fi/okm/jod/yksilo/service/ehdotus/MahdollisuudetService.java
- src/main/resources/schema.sql
- src/test/java/fi/okm/jod/yksilo/controller/TyomahdollisuusControllerTest.java
- src/test/java/fi/okm/jod/yksilo/service/MahdollisuusImportTest.java
- src/test/java/fi/okm/jod/yksilo/service/ehdotus/MahdollisuudetServiceTest.java
- src/test/resources/data/mahdollisuudet-koulutus-delete-import-data.sql
- src/test/resources/data/mahdollisuudet-koulutus-update-import-data-extended.sql
- src/test/resources/data/mahdollisuudet-koulutus-update-import-data-reduced.sql
- src/test/resources/data/mahdollisuudet-tyo-delete-import-data.sql
- src/test/resources/data/mahdollisuudet-tyo-update-import-data-extended.sql
- src/test/resources/data/mahdollisuudet-tyo-update-import-data-reduced.sql
- Added upsert logic to maintain record activity (`Tyomahdollisuus` and `Koulutusmahdollisuus`).
- Introduced an `aktiivinen` boolean field with a default value of true for both entities.
- Applied `@SQLRestriction` to exclude inactive records in database queries.
- Refactored data import and upsert logic for `Tyomahdollisuus` and `Koulutusmahdollisuus`, ensuring outdated records are marked inactive.
- Added tests to verify both `tyomahdollisuus_data.import` and `koulutusmahdollisuus_data.import` SQL procedures.
- Updated unique constraint names and entity structures.
https://jira.eduuni.fi/browse/OPHJOD-1410
> OPHJOD-1410: Change Mahdollisuudet import with upsert logic

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- Updated the default environment from 'dev' to 'development' in the deploy workflow YAML file. This change ensures consistency with the naming conventions across configuration settings.
- Added "Development" in https://github.com/Opetushallitus/jod-yksilo/settings/environments
https://jira.eduuni.fi/browse/OPHJOD-106
> OPHJOD-1063: Set 'development' as default environment in deploy workflow

- src/main/java/fi/okm/jod/yksilo/domain/PolunVaiheLahde.java
- src/main/java/fi/okm/jod/yksilo/dto/profiili/PolunVaiheDto.java
- src/main/java/fi/okm/jod/yksilo/dto/profiili/export/PolunVaiheExportDto.java
- src/main/java/fi/okm/jod/yksilo/entity/PolunVaihe.java
- src/main/java/fi/okm/jod/yksilo/service/profiili/ExportMapper.java
- src/main/java/fi/okm/jod/yksilo/service/profiili/Mapper.java
- src/main/java/fi/okm/jod/yksilo/service/profiili/PolunVaiheService.java
- src/test/java/fi/okm/jod/yksilo/service/profiili/ExportMapperTest.java
- src/test/java/fi/okm/jod/yksilo/service/profiili/PolunVaiheServiceTest.java
Added the `lahde` field to `PolunVaihe` entities and DTOs to distinguish creation types. Introduced `PolunVaiheLahde` enum, updated mappings, services, and tests to ensure support and data consistency.
https://jira.eduuni.fi/browse/OPHJOD-1545
> OPHJOD-1545: Add `lahde` field to `PolunVaihe` entities and DTOs

- src/main/java/fi/okm/jod/yksilo/service/ehdotus/MahdollisuudetService.java
- src/test/java/fi/okm/jod/yksilo/service/ehdotus/MahdollisuudetServiceTest.java
Updated the SQL query to only fetch education opportunities when getting vaihe proposals
https://jira.eduuni.fi/browse/OPHJOD-1552
> OPHJOD-1552: Include education opportunities only when getting vaihe proposals

- src/main/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetController.java
Include the `osaamisia` count when getting ehdotukset for polku. `osaamisia` tells how many comptetences the suggested opportunity provides.
https://jira.eduuni.fi/browse/OPHJOD-1607
> OPHJOD-1607: Include the count of osaamiset the opportunity provides when returning ehdotukset

- src/main/java/fi/okm/jod/yksilo/config/mapping/MappingConfig.java
- src/test/java/fi/okm/jod/yksilo/config/mapping/MappingConfigTest.java
Customizes default Objectmapper to enforce limits on JSON document size.
https://jira.eduuni.fi/browse/OPHJOD-2001
> OPHJOD-2001: Limit maximum JSON request size
