.github/pull_request_template.md

Add pull request template to project.
https://jira.eduuni.fi/browse/OPHJOD-166

OPHJOD-166: Add pull request template

---

LICENSE
README.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
gradlew.bat
src/main/java/fi/okm/jod/yksilo/Main.java
src/main/java/fi/okm/jod/yksilo/config/AwsTracingConfig.java
src/main/java/fi/okm/jod/yksilo/config/OpenApiConfig.java
src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java
src/main/java/fi/okm/jod/yksilo/controller/PingController.java
src/test/java/fi/okm/jod/yksilo/controller/PingControllerTest.java

Update license
https://jira.eduuni.fi/browse/OPHJOD-146

OPHJOD-146: Update license

---

.github/workflows/build.yml
build.gradle
gradle.properties

**Description**
Change Sonar analysis to use CI-based configuration
https://jira.eduuni.fi/browse/OPHJOD-213

OPHJOD-213: Update Sonar analysis

---

build.gradle
src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java

**Description**
Add default CSP and Cache-Control HTTP headers to responses
https://jira.eduuni.fi/browse/OPHJOD-219

OPHJOD-219: Add CSP and Cache-Control HTTP headers

---

.github/workflows/build.yml
docker/Dockerfile

**Description**
Make it possible to use a read-only container filesystem
https://jira.eduuni.fi/browse/OPHJOD-247

OPHJOD-247: Support read-only container root filesystem

---

src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java

- Move headers writer to config
https://jira.eduuni.fi/browse/OPHJOD-219

OPHJOD-219: Move headers writer to config

---

src/main/java/fi/okm/jod/yksilo/config/elasticache/IamAuthTokenRequest.java
src/main/java/fi/okm/jod/yksilo/config/elasticache/RedisIamAuthCredentialsProvider.java
src/test/java/fi/okm/jod/yksilo/config/elasticache/IamAuthTokenRequestTest.java
src/test/java/fi/okm/jod/yksilo/config/elasticache/RedisIamAuthCredentialsProviderTest.java
src/test/java/fi/okm/jod/yksilo/config/elasticache/SessionConfigTest.java

**Description**
Refactor tests to not use mocks
https://jira.eduuni.fi/browse/OPHJOD-229

OPHJOD-229: Remove mocks in tests

---

.github/workflows/build.yml
build.gradle
compose.yml
src/main/java/fi/okm/jod/yksilo/config/AwsConfig.java
src/main/java/fi/okm/jod/yksilo/config/datasource/RdsIamAuthHikariDataSource.java
src/main/resources/application-cloud.yml
src/test/java/fi/okm/jod/yksilo/config/SessionConfigTest.java
src/test/java/fi/okm/jod/yksilo/config/datasource/RdsIamAuthHikariDataSourceTest.java

- Add data access layer
https://jira.eduuni.fi/browse/OPHJOD-249

OPHJOD-249: Add data access layer

---

build.gradle
src/main/java/fi/okm/jod/yksilo/Application.java
src/main/java/fi/okm/jod/yksilo/config/DemoConfig.java
src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java
src/main/java/fi/okm/jod/yksilo/controller/DemoController.java
src/main/java/fi/okm/jod/yksilo/entity/DemoEntity.java
src/main/java/fi/okm/jod/yksilo/repository/DemoRepository.java
src/main/java/fi/okm/jod/yksilo/service/DemoService.java
src/main/resources/application.yml

- Add Spring JPA and demo
https://jira.eduuni.fi/browse/OPHJOD-272

OPHJOD-272: Add Spring JPA and demo API endpoint

---

build.gradle
gradle/config/spotbugs/exclusions.xml
src/main/java/fi/okm/jod/yksilo/config/SessionConfig.java
src/main/java/fi/okm/jod/yksilo/config/datasource/RdsIamAuthHikariDataSource.java
src/test/java/fi/okm/jod/yksilo/ApplicationTest.java
src/test/java/fi/okm/jod/yksilo/config/SessionConfigTest.java

- Limit maximum concurrent sessions
https://jira.eduuni.fi/browse/OPHJOD-248

OPHJOD-248: Limit maximum concurrent sessions

---

.github/workflows/build.yml
src/main/java/fi/okm/jod/yksilo/config/SessionConfig.java
src/main/resources/application.yml
src/test/java/fi/okm/jod/yksilo/config/SessionConfigTest.java
src/test/resources/application-default.yml
src/test/resources/logback-test.xml

- Deployment did not notice deployment failure that caused a rollback
- Remove concurrent sessions limit (does not work)
https://jira.eduuni.fi/browse/OPHJOD-278

OPHJOD-278

---

build.gradle
gradle/config/spotbugs/exclusions.xml
gradle/wrapper/gradle-wrapper.properties
src/main/java/fi/okm/jod/yksilo/config/AwsConfig.java
src/main/java/fi/okm/jod/yksilo/config/OpenApiConfig.java
src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java
src/main/java/fi/okm/jod/yksilo/config/SessionConfig.java
src/main/java/fi/okm/jod/yksilo/controller/DemoController.java
src/main/java/fi/okm/jod/yksilo/controller/OsaamisetEhdotusController.java
src/main/java/fi/okm/jod/yksilo/controller/PingController.java
src/main/java/fi/okm/jod/yksilo/controller/ehdotus/NormalizedString.java
src/main/java/fi/okm/jod/yksilo/controller/ehdotus/OsaamisetController.java
src/main/java/fi/okm/jod/yksilo/controller/ehdotus/TyomahdollisuudetController.java
src/main/java/fi/okm/jod/yksilo/controller/errorhandler/ErrorInfo.java
src/main/java/fi/okm/jod/yksilo/controller/errorhandler/ErrorInfoFactory.java
src/main/java/fi/okm/jod/yksilo/controller/errorhandler/ExceptionHandlerAdvice.java
src/main/java/fi/okm/jod/yksilo/controller/errorhandler/FallbackErrorController.java
src/main/java/fi/okm/jod/yksilo/dto/NormalizedString.java
src/main/java/fi/okm/jod/yksilo/service/ServiceException.java
src/main/java/fi/okm/jod/yksilo/service/ServiceOverloadedException.java
src/main/java/fi/okm/jod/yksilo/service/inference/InferenceService.java
src/main/java/fi/okm/jod/yksilo/service/inference/RestInferenceService.java
src/main/java/fi/okm/jod/yksilo/service/inference/SageMakerInferenceService.java
src/main/java/fi/okm/jod/yksilo/validator/NormalizedStringSizeValidator.java
src/main/resources/META-INF/services/jakarta.validation.ConstraintValidator
src/main/resources/application-cloud.yml
src/main/resources/application.yml
src/test/java/fi/okm/jod/yksilo/config/SessionConfigTest.java
src/test/java/fi/okm/jod/yksilo/controller/PingControllerTest.java

Add mock endpoint for skill recommendation
https://jira.eduuni.fi/browse/OPHJOD-311

OPHJOD-311: Add mock endpoint for skill recommendation

---

build.gradle
src/main/java/fi/okm/jod/yksilo/config/datasource/FlywayDataSourceConfig.java
src/main/java/fi/okm/jod/yksilo/config/datasource/RdsIamAuthHikariDataSource.java
src/main/java/fi/okm/jod/yksilo/config/datasource/RdsIamAuthTokenProvider.java
src/main/resources/application.yml
src/test/java/fi/okm/jod/yksilo/ApplicationTest.java
src/test/java/fi/okm/jod/yksilo/config/datasource/RdsAuthTokenProviderTest.java

Initial support for Flyway migrations.
https://jira.eduuni.fi/browse/OPHJOD-377

OPHJOD-377: Initial support for Flyway migrations

---

gradle/config/spotbugs/exclusions.xml
src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java
src/main/java/fi/okm/jod/yksilo/config/TomcatCustomizer.java
src/main/java/fi/okm/jod/yksilo/controller/CsrfController.java
src/main/java/fi/okm/jod/yksilo/errorhandler/ErrorInfo.java
src/main/java/fi/okm/jod/yksilo/errorhandler/ErrorInfoFactory.java
src/main/java/fi/okm/jod/yksilo/errorhandler/ExceptionHandlerAdvice.java
src/main/java/fi/okm/jod/yksilo/errorhandler/FallbackErrorController.java
src/main/java/fi/okm/jod/yksilo/errorhandler/TomcatErrorReportValve.java
src/test/java/fi/okm/jod/yksilo/controller/CsrfControllerTest.java
src/test/java/fi/okm/jod/yksilo/errorhandler/ErrorHandlingTest.java
src/test/resources/application-default.yml

Add CSRF protection and a mock authentication implementation. Improve error reporting.
https://jira.eduuni.fi/browse/OPHJOD-385

OPHJOD-385

---

src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java
src/main/java/fi/okm/jod/yksilo/config/SessionConfig.java

Support clustered Redis (fixes session replication).
https://jira.eduuni.fi/browse/OPHJOD-388

OPHJOD-388: Support clustered Redis

---

src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java
src/main/java/fi/okm/jod/yksilo/controller/CsrfController.java
src/main/java/fi/okm/jod/yksilo/controller/ehdotus/OsaamisetController.java
src/main/java/fi/okm/jod/yksilo/controller/ehdotus/TyomahdollisuudetController.java
src/main/resources/application.yml

Enforce a maximum duration for a session
https://jira.eduuni.fi/browse/OPHJOD-392

OPHJOD-392: Enforce a maximum duration for a session

---

build.gradle
src/main/resources/application-cloud.yml

Publish application metrics to CloudWatch
https://jira.eduuni.fi/browse/OPHJOD-394

OPHJOD-394: Publish metrics to CloudWatch

---

build.gradle
gradle/config/spotbugs/exclusions.xml
src/main/java/fi/okm/jod/yksilo/config/OpenApiConfig.java
src/main/java/fi/okm/jod/yksilo/config/mapping/LocalizedStringMixin.java
src/main/java/fi/okm/jod/yksilo/controller/ehdotus/OsaamisetEhdotusController.java
src/main/java/fi/okm/jod/yksilo/controller/profiili/KoulutusController.java
src/main/java/fi/okm/jod/yksilo/controller/profiili/YksilonOsaaminenController.java
src/main/java/fi/okm/jod/yksilo/domain/LocalizedString.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/KategoriaDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/KoulutusKategoriaDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/KoulutusUpdateResultDto.java
src/main/java/fi/okm/jod/yksilo/entity/Kategoria.java
src/main/java/fi/okm/jod/yksilo/entity/Koulutus.java
src/main/java/fi/okm/jod/yksilo/entity/KoulutusKategoria.java
src/main/java/fi/okm/jod/yksilo/entity/Tyopaikka.java
src/main/java/fi/okm/jod/yksilo/entity/Yksilo.java
src/main/java/fi/okm/jod/yksilo/entity/YksilonOsaaminen.java
src/main/java/fi/okm/jod/yksilo/errorhandler/ExceptionHandlerAdvice.java
src/main/java/fi/okm/jod/yksilo/repository/KategoriaRepository.java
src/main/java/fi/okm/jod/yksilo/repository/KoulutusKategoriaRepository.java
src/main/java/fi/okm/jod/yksilo/repository/KoulutusRepository.java
src/main/java/fi/okm/jod/yksilo/repository/OsaaminenRepository.java
src/main/java/fi/okm/jod/yksilo/service/ehdotus/OsaamisetEhdotusService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/KoulutusService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/Mapper.java
src/main/java/fi/okm/jod/yksilo/service/profiili/YksilonOsaaminenService.java
src/main/java/fi/okm/jod/yksilo/validation/Limits.java
src/main/resources/application.yml
src/test/java/fi/okm/jod/yksilo/service/KoulutusServiceTest.java

Add backend API for Koulutus
https://jira.eduuni.fi/browse/OPHJOD-430

OPHJOD-430: Add backend API for Koulutus

---

src/main/java/fi/okm/jod/yksilo/controller/profiili/KoulutusController.java

https://jira.eduuni.fi/browse/OPHJOD-468

OPHJOD-468: Rename delete endpoint path

---

src/main/java/fi/okm/jod/yksilo/controller/profiili/KoulutusController.java

- Make some fixes to koulutus API
https://jira.eduuni.fi/browse/OPHJOD-486

OPHJOD-486: Make some fixes to koulutus API

---

src/main/java/fi/okm/jod/yksilo/controller/profiili/ToimintoController.java
src/main/java/fi/okm/jod/yksilo/domain/OsaamisenLahdeTyyppi.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/PatevyysDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/ToimintoDto.java
src/main/java/fi/okm/jod/yksilo/entity/OsaamisenLahde.java
src/main/java/fi/okm/jod/yksilo/entity/Patevyys.java
src/main/java/fi/okm/jod/yksilo/entity/Toiminto.java
src/main/java/fi/okm/jod/yksilo/entity/YksilonOsaaminen.java
src/main/java/fi/okm/jod/yksilo/errorhandler/ExceptionHandlerAdvice.java
src/main/java/fi/okm/jod/yksilo/repository/PatevyysRepository.java
src/main/java/fi/okm/jod/yksilo/repository/ToimintoRepository.java
src/main/java/fi/okm/jod/yksilo/service/profiili/Mapper.java
src/main/java/fi/okm/jod/yksilo/service/profiili/PatevyysService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/ToimintoService.java
src/main/java/fi/okm/jod/yksilo/validation/Limits.java
src/test/java/fi/okm/jod/yksilo/controller/profiili/ToimintoControllerTest.java
src/test/java/fi/okm/jod/yksilo/service/ToimintoServiceTest.java

- Add backend API for Toiminto
https://jira.eduuni.fi/browse/OPHJOD-490

OPHJOD-490: Add backend API for Toiminto

---

src/main/java/fi/okm/jod/yksilo/service/profiili/PatevyysService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/ToimenkuvaService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/TyopaikkaService.java

- Add missing fields
https://jira.eduuni.fi/browse/OPHJOD-523

OPHJOD-523: Add missing fields

---

src/main/java/fi/okm/jod/yksilo/service/profiili/ToimintoService.java

- Fix patevyydet updating
https://jira.eduuni.fi/browse/OPHJOD-523

OPHJOD-523: Fix patevyydet updating

---

README.md

Include link to additional developer documentation
https://jira.eduuni.fi/browse/OPHJOD-493

OPHJOD-493: Update readme

---

src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java
src/main/java/fi/okm/jod/yksilo/controller/TyomahdollisuusController.java
src/main/java/fi/okm/jod/yksilo/dto/SivuDto.java
src/main/java/fi/okm/jod/yksilo/dto/TyomahdollisuusDto.java
src/main/java/fi/okm/jod/yksilo/entity/Tyomahdollisuus.java
src/main/java/fi/okm/jod/yksilo/repository/TyomahdollisuusRepository.java
src/main/java/fi/okm/jod/yksilo/service/TyomahdollisuusService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/Mapper.java
src/main/resources/data.sql

- Add API for Tyomahdollisuus
https://jira.eduuni.fi/browse/OPHJOD-461

OPHJOD-461: Add API for Tyomahdollisuus

---

src/main/java/fi/okm/jod/yksilo/config/elasticache/IamAuthTokenRequest.java

- Suppress deprecation warnings for Aws4Signer
https://jira.eduuni.fi/browse/OPHJOD-527

OPHJOD-527: Suppress deprecation warnings for Aws4Signer

---

src/main/java/fi/okm/jod/yksilo/controller/KuvaController.java
src/main/java/fi/okm/jod/yksilo/controller/YksiloController.java
src/main/java/fi/okm/jod/yksilo/dto/YksiloCsrfDto.java
src/main/java/fi/okm/jod/yksilo/dto/YksiloDto.java
src/main/java/fi/okm/jod/yksilo/entity/Kuva.java
src/main/java/fi/okm/jod/yksilo/entity/Yksilo.java
src/main/java/fi/okm/jod/yksilo/repository/KuvaRepository.java
src/main/java/fi/okm/jod/yksilo/service/KuvaService.java
src/main/java/fi/okm/jod/yksilo/service/YksiloService.java
src/main/resources/application.yml

- Add possibility to add image
https://jira.eduuni.fi/browse/OPHJOD-536

OPHJOD-536: Add possibility to add image

---

src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java
src/main/java/fi/okm/jod/yksilo/controller/TyomahdollisuusController.java
src/main/java/fi/okm/jod/yksilo/domain/JakaumaTyyppi.java
src/main/java/fi/okm/jod/yksilo/dto/ArvoDto.java
src/main/java/fi/okm/jod/yksilo/dto/JakaumaDto.java
src/main/java/fi/okm/jod/yksilo/dto/TyomahdollisuusFullDto.java
src/main/java/fi/okm/jod/yksilo/entity/Jakauma.java
src/main/java/fi/okm/jod/yksilo/entity/Tyomahdollisuus.java
src/main/java/fi/okm/jod/yksilo/repository/TyomahdollisuusRepository.java
src/main/java/fi/okm/jod/yksilo/service/TyomahdollisuusService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/Mapper.java
src/main/resources/application-cloud.yml
src/main/resources/data-import.sql
src/main/resources/data.sql
src/main/resources/esco-import.sql

Add database tables for Tyomahdollisuus. Add endpoint for retrieving detailed information.
https://jira.eduuni.fi/browse/OPHJOD-459

OPHJOD-459: Add database table for Tyomahdollisuus

---

src/main/java/fi/okm/jod/yksilo/controller/YksiloController.java
src/main/java/fi/okm/jod/yksilo/dto/CsrfTokenDto.java

- Fix CSRF typings
https://jira.eduuni.fi/browse/OPHJOD-536

OPHJOD-536: Fix CSRF typings

---

src/main/java/fi/okm/jod/yksilo/dto/TyomahdollisuusDto.java
src/main/java/fi/okm/jod/yksilo/dto/TyomahdollisuusFullDto.java

Fix OpenAPI description
https://jira.eduuni.fi/browse/OPHJOD-459

OPHJOD-459: Fix OpenAPI description

---

src/main/java/fi/okm/jod/yksilo/controller/YksiloController.java
src/main/java/fi/okm/jod/yksilo/entity/Koulutus.java
src/main/java/fi/okm/jod/yksilo/entity/KoulutusKategoria.java
src/main/java/fi/okm/jod/yksilo/entity/Kuva.java
src/main/java/fi/okm/jod/yksilo/entity/Toiminto.java
src/main/java/fi/okm/jod/yksilo/entity/Tyopaikka.java
src/main/java/fi/okm/jod/yksilo/entity/Yksilo.java
src/main/java/fi/okm/jod/yksilo/service/YksiloService.java

- Add API for deleting user
https://jira.eduuni.fi/browse/OPHJOD-535

OPHJOD-535: Add API for user deleting

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Add deploy workflow
https://jira.eduuni.fi/browse/OPHJOD-538

OPHJOD-583: Add workflow for deploying to test env

---

.github/workflows/build.yml
build.gradle
src/main/java/fi/okm/jod/yksilo/config/elasticache/IamAuthTokenRequest.java
src/test/java/fi/okm/jod/yksilo/config/elasticache/IamAuthTokenRequestTest.java

Replace deprecated Aws4Signer with AwsV4HttpSigner
https://jira.eduuni.fi/browse/OPHJOD-551

OPHJOD-551: Replace deprecated Aws4Signer

---

src/main/java/fi/okm/jod/yksilo/config/mocklogin/MockLoginConfig.java

Fix mock login conditional configuration
https://jira.eduuni.fi/browse/OPHJOD-212

OPHJOD-212: Fix configuration condition

---

build.gradle
src/main/java/fi/okm/jod/yksilo/controller/OsaaminenController.java
src/main/java/fi/okm/jod/yksilo/controller/TyomahdollisuusController.java
src/main/java/fi/okm/jod/yksilo/controller/ehdotus/TyomahdollisuudetController.java
src/main/java/fi/okm/jod/yksilo/repository/TyomahdollisuusRepository.java
src/main/java/fi/okm/jod/yksilo/service/OsaaminenService.java
src/main/java/fi/okm/jod/yksilo/service/TyomahdollisuusService.java
src/main/java/fi/okm/jod/yksilo/service/ehdotus/OsaamisetEhdotusService.java
src/main/resources/data-import.sql

Update tyomahdollisuus recommendation/suggestion endpoint to work with the latest inference endpoint (see https://github.com/petushallitus/jod-yksilo-kohtaanto/pull/29)
https://jira.eduuni.fi/browse/OPHJOD-643

OPHJOD-643: Update tyomahdollisuus recommendation endpoint

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Use secrets in workflows
https://jira.eduuni.fi/browse/OPHJOD-608

OPHJOD-608: Use secrets in workflows

---

src/main/java/fi/okm/jod/yksilo/config/datasource/HibernateSchemaFilterProvider.java
src/main/java/fi/okm/jod/yksilo/entity/Jakauma.java
src/main/java/fi/okm/jod/yksilo/entity/Tyomahdollisuus.java
src/main/resources/application.yml
src/main/resources/data-import.sql
src/test/resources/application-default.yml

Use tyomahdollisuus from a separate schema.
Excludes the externally created schema from Hiberate DDL operations.
https://jira.eduuni.fi/browse/OPHJOD-694

OPHJOD-694: Use tyomahdollisuus from a separate schema.

---

.gitignore
scripts/init-local-env.sh

Simplify running backend in local development environment
https://jira.eduuni.fi/browse/OPHJOD-715

OPHJOD-715: Add local profile for backend

---

src/main/java/fi/okm/jod/yksilo/controller/profiili/ToimintoController.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/PatevyysDto.java
src/main/java/fi/okm/jod/yksilo/entity/Patevyys.java
src/main/java/fi/okm/jod/yksilo/service/profiili/Mapper.java
src/main/java/fi/okm/jod/yksilo/service/profiili/PatevyysService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/ToimintoService.java
src/test/java/fi/okm/jod/yksilo/controller/profiili/ToimintoControllerTest.java
src/test/java/fi/okm/jod/yksilo/service/ToimintoServiceTest.java

Fix toiminto API
https://jira.eduuni.fi/browse/OPHJOD-457

OPHJOD-457: Fix toiminto API

---

scripts/git-hooks/pre-push
src/main/java/fi/okm/jod/yksilo/controller/profiili/YksiloController.java
src/main/java/fi/okm/jod/yksilo/service/profiili/YksiloService.java
src/test/java/fi/okm/jod/yksilo/controller/profiili/YksiloControllerTest.java

Remove /api/yksilo (moved to /api/profiili/yksilo)
See also: https://github.com/Opetushallitus/jod-yksilo-ui/pull/161
https://jira.eduuni.fi/browse/OPHJOD-782

OPHJOD-782: Remove /api/yksilo

---

src/main/java/fi/okm/jod/yksilo/controller/profiili/KiinnostusController.java
src/main/java/fi/okm/jod/yksilo/entity/Yksilo.java
src/main/java/fi/okm/jod/yksilo/repository/YksiloRepository.java
src/main/java/fi/okm/jod/yksilo/service/profiili/KiinnostusService.java
src/test/java/fi/okm/jod/yksilo/service/AbstractServiceTest.java
src/test/java/fi/okm/jod/yksilo/service/profiili/KiinnostusServiceTest.java

Add API for kiinnostukset
https://jira.eduuni.fi/browse/OPHJOD-784

OPHJOD-784: Add API for kiinnostukset

---

src/test/java/fi/okm/jod/yksilo/service/KoulutusServiceTest.java
src/test/java/fi/okm/jod/yksilo/service/PatevyysServiceTest.java

Fix test method naming
https://jira.eduuni.fi/browse/OPHJOD-725

OPHJOD-725: Fix test method naming

---

build.gradle
src/main/java/fi/okm/jod/yksilo/config/mapping/MappingConfig.java
src/main/java/fi/okm/jod/yksilo/controller/profiili/MuuOsaaminenController.java
src/main/java/fi/okm/jod/yksilo/domain/MuuOsaaminen.java
src/main/java/fi/okm/jod/yksilo/domain/OsaamisenLahde.java
src/main/java/fi/okm/jod/yksilo/domain/OsaamisenLahdeTyyppi.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/OsaamisenLahdeDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/YksilonOsaaminenDto.java
src/main/java/fi/okm/jod/yksilo/entity/Koulutus.java
src/main/java/fi/okm/jod/yksilo/entity/Patevyys.java
src/main/java/fi/okm/jod/yksilo/entity/Toimenkuva.java
src/main/java/fi/okm/jod/yksilo/entity/YksilonOsaaminen.java
src/main/java/fi/okm/jod/yksilo/repository/KoulutusRepository.java
src/main/java/fi/okm/jod/yksilo/repository/OsaamisenLahdeRepository.java
src/main/java/fi/okm/jod/yksilo/repository/PatevyysRepository.java
src/main/java/fi/okm/jod/yksilo/repository/ToimenkuvaRepository.java
src/main/java/fi/okm/jod/yksilo/service/profiili/Mapper.java
src/main/java/fi/okm/jod/yksilo/service/profiili/MuuOsaaminenService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/YksilonOsaaminenService.java
src/test/java/fi/okm/jod/yksilo/service/AbstractServiceTest.java
src/test/java/fi/okm/jod/yksilo/service/MuuOsaaminenServiceTest.java
src/test/java/fi/okm/jod/yksilo/service/YksilonOsaaminenServiceTest.java
src/test/resources/data/osaaminen.sql

Muu osaaminen API.
/api/profiili/muu-osaaminen
GET & PUT
https://jira.eduuni.fi/browse/OPHJOD-785

OPHJOD-785: Add muu osaaminen API

---

src/main/java/fi/okm/jod/yksilo/controller/ehdotus/TyomahdollisuudetController.java

Fix sort order
https://jira.eduuni.fi/browse/OPHJOD-810

OPHJOD-810: Fix suggestion sort order

---

src/main/java/fi/okm/jod/yksilo/entity/KoulutusKokonaisuus.java
src/main/java/fi/okm/jod/yksilo/entity/Toiminto.java
src/main/java/fi/okm/jod/yksilo/entity/Tyopaikka.java
src/main/java/fi/okm/jod/yksilo/entity/YksilonOsaaminen.java
src/main/java/fi/okm/jod/yksilo/repository/YksilonOsaaminenRepository.java

Optimize fetch from DB.
Also removes some unused fields.
https://jira.eduuni.fi/browse/OPHJOD-820

OPHJOD-820: Optimize fetch from DB.

---

src/main/java/fi/okm/jod/yksilo/controller/profiili/YksilonSuosikkiController.java
src/main/java/fi/okm/jod/yksilo/domain/SuosikkiTyyppi.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/SuosikkiDto.java
src/main/java/fi/okm/jod/yksilo/entity/Yksilo.java
src/main/java/fi/okm/jod/yksilo/entity/YksilonSuosikki.java
src/main/java/fi/okm/jod/yksilo/repository/YksilonSuosikkiRepository.java
src/main/java/fi/okm/jod/yksilo/service/profiili/YksilonSuosikkiService.java
src/test/java/fi/okm/jod/yksilo/service/profiili/YksilonSuosikkiServiceTest.java
src/test/resources/data/create/yksilon-suosikki-test-data.sql

Implementation of API to handle favorites of the yksilö.
https://jira.eduuni.fi/browse/OPHJOD-812

OPHJOD-812: Add yksilön suosikki API

---

src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java
src/main/java/fi/okm/jod/yksilo/controller/KoulutusmahdollisuusController.java
src/main/java/fi/okm/jod/yksilo/domain/KoulutusmahdollisuusJakaumaTyyppi.java
src/main/java/fi/okm/jod/yksilo/domain/KoulutusmahdollisuusTyyppi.java
src/main/java/fi/okm/jod/yksilo/domain/TyomahdollisuusJakaumaTyyppi.java
src/main/java/fi/okm/jod/yksilo/dto/KestoJakaumaDto.java
src/main/java/fi/okm/jod/yksilo/dto/KoulutusViiteDto.java
src/main/java/fi/okm/jod/yksilo/dto/KoulutusmahdollisuusDto.java
src/main/java/fi/okm/jod/yksilo/dto/KoulutusmahdollisuusFullDto.java
src/main/java/fi/okm/jod/yksilo/entity/YksilonSuosikki.java
src/main/java/fi/okm/jod/yksilo/entity/koulutusmahdollisuus/KoulutusViite.java
src/main/java/fi/okm/jod/yksilo/entity/koulutusmahdollisuus/Koulutusmahdollisuus.java
src/main/java/fi/okm/jod/yksilo/entity/koulutusmahdollisuus/KoulutusmahdollisuusJakauma.java
src/main/java/fi/okm/jod/yksilo/entity/tyomahdollisuus/Tyomahdollisuus.java
src/main/java/fi/okm/jod/yksilo/entity/tyomahdollisuus/TyomahdollisuusJakauma.java
src/main/java/fi/okm/jod/yksilo/repository/KoulutusmahdollisuusRepository.java
src/main/java/fi/okm/jod/yksilo/repository/TyomahdollisuusRepository.java
src/main/java/fi/okm/jod/yksilo/repository/YksilonOsaaminenRepository.java
src/main/java/fi/okm/jod/yksilo/service/JakaumaMapper.java
src/main/java/fi/okm/jod/yksilo/service/KoulutusmahdollisuusService.java
src/main/java/fi/okm/jod/yksilo/service/TyomahdollisuusService.java
src/main/resources/application.yml

Add API and entities for Koulutusmahdollisuus
https://jira.eduuni.fi/browse/OPHJOD-838

OPHJOD-838: Add API and entities for Koulutusmahdollisuus

---

src/main/resources/schema.sql
src/test/resources/data/mahdollisuudet.sql

Fix koulutusmahdollisuus import
https://jira.eduuni.fi/browse/OPHJOD-898

OPHJOD-898: Fix koulutusmahdollisuus import

---

src/main/java/fi/okm/jod/yksilo/controller/profiili/YksilonSuosikkiController.java
src/main/java/fi/okm/jod/yksilo/entity/YksilonSuosikki.java
src/main/java/fi/okm/jod/yksilo/entity/koulutusmahdollisuus/Koulutusmahdollisuus.java
src/main/java/fi/okm/jod/yksilo/repository/YksilonSuosikkiRepository.java
src/main/java/fi/okm/jod/yksilo/service/profiili/KiinnostusService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/YksilonSuosikkiService.java
src/test/java/fi/okm/jod/yksilo/service/profiili/YksilonSuosikkiServiceTest.java
src/test/resources/data/create/yksilon-suosikki-test-data.sql

Add Koulutusmahdollisuus as Suosikki
https://jira.eduuni.fi/browse/OPHJOD-858

OPHJOD-858

---

src/main/java/fi/okm/jod/yksilo/controller/ehdotus/TyomahdollisuudetController.java

Changed EhdotusMetadata optional properties to nullable
https://jira.eduuni.fi/browse/OPHJOD-859

OPHJOD-859: EhdotusMetadata optional properties changed to nullable

---

.github/workflows/build.yml
build.gradle
compose-test.yml
src/main/java/fi/okm/jod/yksilo/entity/koulutusmahdollisuus/KoulutusmahdollisuusJakauma.java
src/main/java/fi/okm/jod/yksilo/entity/tyomahdollisuus/TyomahdollisuusJakauma.java

Adds a Gradle task that generates the DB schema diagram using SchemaSpy.
https://jira.eduuni.fi/browse/OPHJOD-846

OPHJOD-846: Generate DB schema diagram

---

scripts/init-local-env.sh
src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java
src/main/java/fi/okm/jod/yksilo/controller/AmmattiController.java
src/main/java/fi/okm/jod/yksilo/controller/ETags.java
src/main/java/fi/okm/jod/yksilo/domain/Versioned.java
src/main/java/fi/okm/jod/yksilo/dto/AmmattiDto.java
src/main/java/fi/okm/jod/yksilo/entity/Ammatti.java
src/main/java/fi/okm/jod/yksilo/entity/AmmattiVersio.java
src/main/java/fi/okm/jod/yksilo/repository/AmmattiRepository.java
src/main/java/fi/okm/jod/yksilo/service/AmmattiService.java
src/main/java/fi/okm/jod/yksilo/service/OsaaminenService.java
src/main/resources/data.sql
src/main/resources/schema.sql
src/test/java/fi/okm/jod/yksilo/service/AmmattiServiceTest.java
src/test/resources/data/ammatti.sql
src/test/resources/data/mock-tunnistus.sql

Add /api/ammatit for retrieving information about occupations
https://jira.eduuni.fi/browse/OPHJOD-900

OPHJOD-900: Add /api/ammatit

---

src/main/java/fi/okm/jod/yksilo/dto/TyomahdollisuusFullDto.java
src/main/java/fi/okm/jod/yksilo/entity/tyomahdollisuus/Tyomahdollisuus.java
src/main/java/fi/okm/jod/yksilo/service/TyomahdollisuusService.java
src/main/resources/schema.sql

Tyomahdollisuus update to new schema 
new fields:
- ammattiryhma
- tehtavat
- yleisetVaatimukset
https://jira.eduuni.fi/browse/OPHJOD-483

OPHJOD-483: Update tyomahdollisuudet to new schema

---

build.gradle
src/main/java/fi/okm/jod/yksilo/config/mocklogin/MockLoginController.java
src/main/java/fi/okm/jod/yksilo/config/suomifi/LoginController.java
src/main/resources/application-cloud.yml
src/main/resources/application.yml
src/test/java/fi/okm/jod/yksilo/errorhandler/ErrorHandlingTest.java

- Update context path
https://jira.eduuni.fi/browse/OPHJOD-1053

OPHJOD-1053: Update context path

---

src/main/java/fi/okm/jod/yksilo/service/ehdotus/MahdollisuudetService.java

Improve SQL query to use collation by selected language
https://jira.eduuni.fi/browse/OPHJOD-1133

OPHJOD-1133: Fix collation by selected locale

---

src/main/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetController.java
src/main/java/fi/okm/jod/yksilo/entity/Yksilo.java
src/main/java/fi/okm/jod/yksilo/repository/AmmattiRepository.java
src/main/java/fi/okm/jod/yksilo/repository/YksiloRepository.java
src/main/java/fi/okm/jod/yksilo/service/AmmattiService.java
src/main/java/fi/okm/jod/yksilo/service/ehdotus/OsaamisetEhdotusService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/KiinnostusService.java
src/test/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetControllerTest.java

- Add occupations for suggestions
https://jira.eduuni.fi/browse/OPHJOD-1125

OPHJOD-1125: Add occupations for suggestions

---

src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java
src/main/java/fi/okm/jod/yksilo/controller/KeskusteluController.java
src/main/java/fi/okm/jod/yksilo/service/inference/InferenceService.java
src/main/java/fi/okm/jod/yksilo/service/inference/RestInferenceService.java
src/main/java/fi/okm/jod/yksilo/service/inference/SageMakerInferenceService.java
src/main/resources/application.yml

- Add virtual assistant
https://jira.eduuni.fi/browse/OPHJOD-1143

OPHJOD-1143: Add virtual assistant

---

scripts/init-local-env.sh
src/main/java/fi/okm/jod/yksilo/controller/OsaaminenController.java
src/main/java/fi/okm/jod/yksilo/entity/OsaaminenVersio.java
src/main/java/fi/okm/jod/yksilo/repository/OsaaminenRepository.java
src/main/java/fi/okm/jod/yksilo/service/OsaaminenService.java
src/main/resources/schema.sql

Change ESCO skills import to CSV based import format, which allows use of ESCO csv files.
https://jira.eduuni.fi/browse/OPHJOD-1221

OPHJOD-1221: Change esco skill import to CSV based

---

scripts/init-local-env.sh

Refactors init-local-env script. Removes some duplication in database intialization.
https://jira.eduuni.fi/browse/OPHJOD-1221

OPHJOD-1221: Refactor init-local-env

---

src/main/java/fi/okm/jod/yksilo/repository/OsaaminenRepository.java
src/main/resources/data.sql

Fix Osaaminen refresh
https://jira.eduuni.fi/browse/OPHJOD-1221

OPHJOD-1221: Fix Osaaminen refresh

---

scripts/cloud-update-esco-from-s3.sh
scripts/init-local-env.sh

This is an utility script to help update of esco data from s3 to RDS to specific esco version.
Usage of this script requires RDS ssh tunnel and aws credentials. 
https://jira.eduuni.fi/browse/OPHJOD-1221

OPHJOD-1221: Script to update esco skills

---

src/main/java/fi/okm/jod/yksilo/controller/profiili/PaamaaraController.java
src/main/java/fi/okm/jod/yksilo/controller/profiili/YksilonSuosikkiController.java

Fix validation
https://jira.eduuni.fi/browse/OPHJOD-1219

OPHJOD-1219: Fix validation

---

scripts/git-hooks/pre-push

- Update commit message checking
https://jira.eduuni.fi/browse/OPHJOD-1282

OPHJOD-1282: Update commit message checking

---

scripts/cloud-update-esco-from-s3.sh
scripts/update-local-env-data.sh
src/main/resources/schema.sql

Convert the list of tehtävät of työmahdollisuus to a string with individual lines. This keeps the data compatible with the previous backend implementation. 
https://jira.eduuni.fi/browse/OPHJOD-1216

OPHJOD-1216:  Import list of tyomahdollisuus tehtavat

---

src/main/java/fi/okm/jod/yksilo/domain/TyomahdollisuusAineisto.java
src/main/java/fi/okm/jod/yksilo/dto/TyomahdollisuusFullDto.java
src/main/java/fi/okm/jod/yksilo/entity/tyomahdollisuus/Tyomahdollisuus.java
src/main/java/fi/okm/jod/yksilo/service/TyomahdollisuusService.java
src/main/resources/schema.sql
src/test/java/fi/okm/jod/yksilo/service/MahdollisuusImportTest.java
src/test/resources/data/mahdollisuudet-test-data.sql
src/test/resources/data/mahdollisuudet.sql

- Add aineisto for tyomahdollisuus
https://jira.eduuni.fi/browse/OPHJOD-1264

OPHJOD-1264: Add aineisto for tyomahdollisuus

---

src/main/java/fi/okm/jod/yksilo/entity/tyomahdollisuus/Tyomahdollisuus.java

- Refactor Tyomahdollisuus entity
https://jira.eduuni.fi/browse/OPHJOD-1264

OPHJOD-1264: Refactor Tyomahdollisuus entity

---

src/main/java/fi/okm/jod/yksilo/config/koski/KoskiRestClientConfig.java
src/main/java/fi/okm/jod/yksilo/config/koski/KoskiSecurityConfig.java
src/main/java/fi/okm/jod/yksilo/controller/koski/KoskiOAuth2Controller.java
src/main/java/fi/okm/jod/yksilo/errorhandler/FallbackErrorController.java
src/main/java/fi/okm/jod/yksilo/service/koski/KoskiOAuth2Service.java

https://jira.eduuni.fi/browse/OPHJOD-1217

OPHJOD-1217: Refactor configuration and error handling

---

src/main/java/fi/okm/jod/yksilo/controller/profiili/PolunSuunnitelmaController.java
src/main/java/fi/okm/jod/yksilo/controller/profiili/PolunVaiheController.java
src/main/java/fi/okm/jod/yksilo/domain/PolunVaiheTyyppi.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/PaamaaraYhteenvetoDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/PolunSuunnitelmaDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/PolunSuunnitelmaUpdateDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/PolunSuunnitelmaYhteenvetoDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/PolunVaiheDto.java
src/main/java/fi/okm/jod/yksilo/entity/Paamaara.java
src/main/java/fi/okm/jod/yksilo/entity/PolunSuunnitelma.java
src/main/java/fi/okm/jod/yksilo/entity/PolunVaihe.java
src/main/java/fi/okm/jod/yksilo/repository/PolunSuunnitelmaRepository.java
src/main/java/fi/okm/jod/yksilo/repository/PolunVaiheRepository.java
src/main/java/fi/okm/jod/yksilo/service/profiili/Mapper.java
src/main/java/fi/okm/jod/yksilo/service/profiili/PolunSuunnitelmaService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/PolunVaiheService.java
src/main/java/fi/okm/jod/yksilo/validation/Limits.java
src/test/java/fi/okm/jod/yksilo/service/profiili/PaamaaraServiceTest.java
src/test/java/fi/okm/jod/yksilo/service/profiili/PolunSuunnitelmaServiceTest.java
src/test/java/fi/okm/jod/yksilo/service/profiili/PolunVaiheServiceTest.java
src/test/resources/data/mahdollisuudet-test-data.sql

- Add implementation for path
https://jira.eduuni.fi/browse/OPHJOD-1307

OPHJOD-1307: Add implementation for path

---

src/main/java/fi/okm/jod/yksilo/service/koski/KoskiService.java

https://jira.eduuni.fi/browse/OPHJOD-1377

OPHJOD-1377: Remove LocalizeString fallback as Client do it instead

---

src/main/java/fi/okm/jod/yksilo/dto/profiili/KoulutusDto.java

- Remove not null annotation from alkuPvm
https://jira.eduuni.fi/browse/OPHJOD-1380

OPHJOD-1380: Remove not null annotation from alkuPvm

---

src/main/java/fi/okm/jod/yksilo/entity/Yksilo.java
src/test/java/fi/okm/jod/yksilo/controller/profiili/YksiloControllerTest.java
src/test/java/fi/okm/jod/yksilo/service/profiili/YksiloServiceTest.java

- Add paamaarat relationship to Yksilo entity
https://jira.eduuni.fi/browse/OPHJOD-1395

OPHJOD-1395: Add paamaarat relationship to Yksilo entity

---

src/main/java/fi/okm/jod/yksilo/config/suomifi/Attribute.java
src/main/java/fi/okm/jod/yksilo/dto/TyomahdollisuusFullDto.java
src/main/java/fi/okm/jod/yksilo/entity/Ammatti.java
src/main/java/fi/okm/jod/yksilo/entity/Osaaminen.java
src/main/java/fi/okm/jod/yksilo/entity/Paamaara.java
src/main/java/fi/okm/jod/yksilo/entity/UriConverter.java
src/main/java/fi/okm/jod/yksilo/entity/tyomahdollisuus/Tyomahdollisuus.java
src/main/java/fi/okm/jod/yksilo/repository/AmmattiRepository.java
src/main/java/fi/okm/jod/yksilo/repository/OsaaminenRepository.java
src/main/java/fi/okm/jod/yksilo/service/profiili/KiinnostusService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/Mapper.java
src/main/java/fi/okm/jod/yksilo/service/profiili/PolunSuunnitelmaService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/PolunVaiheService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/YksilonOsaaminenService.java

This pull request enhances URI handling to ensure consistency, type safety, and validation.
https://jira.eduuni.fi/browse/OPHJOD-137

OPHJOD-1375: Replace URI String-type to URI-type

---

src/main/java/fi/okm/jod/yksilo/config/SecurityConfig.java

Ignore CSRF when the "local" profile is active.
https://jira.eduuni.fi/browse/OPHJOD-1342

OPHJOD-1342: Ignore CSRF when the "local" profile is active

---

src/main/java/fi/okm/jod/yksilo/repository/OsaaminenRepository.java
src/main/java/fi/okm/jod/yksilo/service/profiili/KoulutusService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/MuuOsaaminenService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/PatevyysService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/PolunSuunnitelmaService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/PolunVaiheService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/ToimenkuvaService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/YksilonOsaaminenService.java
src/test/java/fi/okm/jod/yksilo/service/profiili/PolunSuunnitelmaServiceTest.java
src/test/java/fi/okm/jod/yksilo/service/profiili/PolunVaiheServiceTest.java

Filter duplicates when adding osaaminen to MuuOsaaminen. Refactor.
https://jira.eduuni.fi/browse/OPHJOD-1479

OPHJOD-1479: Fix duplicates when adding MuuOsaaminen

---

src/main/java/fi/okm/jod/yksilo/controller/profiili/YksiloController.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/KoulutusExportDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/KoulutusKokonaisuusExportDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/PaamaaraExportDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/PatevyysExportDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/PolunSuunnitelmaExportDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/PolunVaiheExportDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/ToimenkuvaExportDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/ToimintoExportDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/TyopaikkaExportDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/YksiloExportDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/YksilonSuosikkiExportDto.java
src/main/java/fi/okm/jod/yksilo/entity/Koulutus.java
src/main/java/fi/okm/jod/yksilo/entity/Paamaara.java
src/main/java/fi/okm/jod/yksilo/entity/Patevyys.java
src/main/java/fi/okm/jod/yksilo/entity/PolunSuunnitelma.java
src/main/java/fi/okm/jod/yksilo/entity/PolunVaihe.java
src/main/java/fi/okm/jod/yksilo/entity/Toimenkuva.java
src/main/java/fi/okm/jod/yksilo/entity/Toiminto.java
src/main/java/fi/okm/jod/yksilo/entity/Tyopaikka.java
src/main/java/fi/okm/jod/yksilo/service/profiili/ExportMapper.java
src/main/java/fi/okm/jod/yksilo/service/profiili/YksiloService.java
src/test/java/fi/okm/jod/yksilo/service/profiili/ExportMapperTest.java

- Add export functionality
https://jira.eduuni.fi/browse/OPHJOD-1462

OPHJOD-1462: Add export functionality

---

src/main/java/fi/okm/jod/yksilo/config/ProfileDeletionHandler.java
src/main/java/fi/okm/jod/yksilo/config/mocklogin/MockLoginConfig.java
src/main/java/fi/okm/jod/yksilo/config/suomifi/Saml2LoginConfig.java
src/main/java/fi/okm/jod/yksilo/controller/profiili/YksiloController.java
src/test/java/fi/okm/jod/yksilo/controller/profiili/YksiloControllerTest.java

- Refactor delete method in YksiloController
- See also https://github.com/Opetushallitus/jod-yksilo-ui/pull/410
https://jira.eduuni.fi/browse/OPHJOD-1456

OPHJOD-1456: Refactor delete method in YksiloController

---

src/test/resources/application-default.yml

Disable AWS Secrets Manager for local test runs.
https://jira.eduuni.fi/browse/OPHJOD-1369

OPHJOD-1369: Disable AWS Secrets Manager for local test runs

---

src/main/java/fi/okm/jod/yksilo/controller/profiili/YksiloController.java

- Remove unneeded mapper
https://jira.eduuni.fi/browse/OPHJOD-1462

OPHJOD-1462: Remove unneeded mapper

---

src/main/java/fi/okm/jod/yksilo/service/profiili/PolunSuunnitelmaService.java
src/test/java/fi/okm/jod/yksilo/service/profiili/PolunSuunnitelmaServiceTest.java

- Add restriction to PolunSuunnitelma
https://jira.eduuni.fi/browse/OPHJOD-1508

OPHJOD-1508: Add restriction to PolunSuunnitelma

---

src/main/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetController.java
src/main/java/fi/okm/jod/yksilo/controller/ehdotus/Suggestion.java
src/main/java/fi/okm/jod/yksilo/service/ehdotus/MahdollisuudetService.java
src/main/java/fi/okm/jod/yksilo/service/ehdotus/OsaamisetSuggestion.java
src/test/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetControllerTest.java
src/test/java/fi/okm/jod/yksilo/service/MahdollisuusImportTest.java
src/test/java/fi/okm/jod/yksilo/service/ehdotus/MahdollisuudetServiceTest.java
src/test/resources/data/koulutusmahdollisuudet.sql
src/test/resources/data/tyomahdollisuudet.sql

This pull request introduces several key changes and improvements:
- Added a new POST /api/ehdotus/mahdollisuudet/polku API endpoint for suggesting educational and job opportunities based on missing skills, along with utility methods, SQL queries, and comprehensive test cases.
- Enhanced test coverage for mahdollisuudet suggestions, incorporating new datasets for various scenarios and ensuring the correct order of results.
- Refactored test setup to use SQL scripts and transaction management for clarity and maintainability.
https://jira.eduuni.fi/browse/OPHJOD-1390

OPHJOD-1390: New API endpoint for suggesting educational and job opportunities

---

src/main/java/fi/okm/jod/yksilo/entity/PolunVaihe.java
src/main/java/fi/okm/jod/yksilo/errorhandler/ExceptionHandlerAdvice.java

- Added a default value of 'KAYTTAJA' for the `PolunVaiheLahde` field using `@ColumnDefault` and initialized it in code.
- Enhanced error responses to include field names along with their validation error messages for better client troubleshooting.
https://jira.eduuni.fi/browse/OPHJOD-1589

OPHJOD-1589: Set default value and improve validation error feedback

---

docker/Dockerfile

Update Dockerfile, fix directory permission problem
https://jira.eduuni.fi/browse/OPHJOD-1603

OPHJOD-1603: Update Dockerfile

---

.github/workflows/build.yml
src/main/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetController.java
src/main/java/fi/okm/jod/yksilo/dto/MahdollisuusDto.java
src/main/java/fi/okm/jod/yksilo/dto/PolunVaiheEhdotusDto.java
src/main/java/fi/okm/jod/yksilo/repository/KoulutusmahdollisuusRepository.java
src/main/java/fi/okm/jod/yksilo/repository/TyomahdollisuusRepository.java
src/main/java/fi/okm/jod/yksilo/service/ehdotus/MahdollisuudetService.java
src/main/resources/schema.sql
src/test/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetControllerTest.java
src/test/java/fi/okm/jod/yksilo/service/MahdollisuusImportTest.java
src/test/java/fi/okm/jod/yksilo/service/ehdotus/MahdollisuudetServiceTest.java
src/test/java/fi/okm/jod/yksilo/service/profiili/YksilonSuosikkiServiceTest.java

Fix bug in path step suggestion query. Move queries to a repository.
https://jira.eduuni.fi/browse/OPHJOD-1613

OPHJOD-1613: Fix bug in suggestion query. Refactor.

---

src/main/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetController.java
src/main/java/fi/okm/jod/yksilo/controller/profiili/KiinnostusController.java
src/main/java/fi/okm/jod/yksilo/controller/profiili/MuuOsaaminenController.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/KiinnostuksetDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/MuuOsaaminenDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/YksiloExportDto.java
src/main/java/fi/okm/jod/yksilo/entity/Yksilo.java
src/main/java/fi/okm/jod/yksilo/service/profiili/ExportMapper.java
src/main/java/fi/okm/jod/yksilo/service/profiili/KiinnostusService.java
src/main/java/fi/okm/jod/yksilo/service/profiili/MuuOsaaminenService.java
src/test/java/fi/okm/jod/yksilo/controller/ehdotus/MahdollisuudetControllerTest.java
src/test/java/fi/okm/jod/yksilo/service/MuuOsaaminenServiceTest.java
src/test/java/fi/okm/jod/yksilo/service/profiili/KiinnostusServiceTest.java

- Add Vapaateksti for MuuOsaaminen and Kiinnostus
https://jira.eduuni.fi/browse/OPHJOD-1467

OPHJOD-1467: Add Vapaateksti for MuuOsaaminen and Kiinnostus

---

src/main/java/fi/okm/jod/yksilo/config/LoginSuccessHandler.java

- Improve redirect handling in LoginSuccessHandler
https://jira.eduuni.fi/browse/OPHJOD-1596

OPHJOD-1596: Improve redirect handling in LoginSuccessHandler

---

src/main/java/fi/okm/jod/yksilo/config/datasource/RdsDataSourceConfig.java
src/main/java/fi/okm/jod/yksilo/config/datasource/RdsIamAuthHikariDataSource.java

Fix IAM authentication that was broken due to change to HikariDataSource introduced in HikariCP 6
https://jira.eduuni.fi/browse/OPHJOD-1717

OPHJOD-1717: Fix RDS IAM authentication

---

.gitignore
compose.yml
scripts/init-local-env.sh

- Add local osaamissuosittelija
https://jira.eduuni.fi/browse/OPHJOD-1716

OPHJOD-1716: Add local osaamissuosittelija

---

src/main/java/fi/okm/jod/yksilo/config/OpenApiConfig.java
src/main/java/fi/okm/jod/yksilo/externalapi/v1/ExternalApiV1Controller.java

http://localhost:9080/yksilo/openapi/swagger-ui/index.html?urls.primaryName=External+API#/ dokumentaatio näkyy täällä.

OPHJOD-1749: Group external api in swagger

---

src/main/resources/db/migration/V20250908.2002__add_ammattiryhma_table.sql

OPHJOD-2002: Add table for ammattiryhmat

---

src/main/java/fi/okm/jod/yksilo/dto/profiili/export/KiinnostuksetExportDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/MuuOsaaminenExportDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/YksiloExportDto.java
src/main/java/fi/okm/jod/yksilo/service/profiili/ExportMapper.java
src/test/java/fi/okm/jod/yksilo/service/profiili/ExportMapperTest.java

Add muuOsaaminen to exported profile data. Refactor.
https://jira.eduuni.fi/browse/OPHJOD-1909

OPHJOD-1909: Fix muuOsaaminen not exported

---

src/main/java/fi/okm/jod/yksilo/controller/AmmattiController.java
src/main/java/fi/okm/jod/yksilo/controller/KoulutusmahdollisuusController.java
src/main/java/fi/okm/jod/yksilo/controller/OsaaminenController.java
src/main/java/fi/okm/jod/yksilo/controller/TyomahdollisuusController.java
src/main/java/fi/okm/jod/yksilo/service/OsaaminenService.java
tmt-mock/build.gradle

Fix paged requests do not validate page and page size limits
https://jira.eduuni.fi/browse/OPHJOD-1993

OPHJOD-1993: Fix paged requests do not validate limits

---

src/main/java/fi/okm/jod/yksilo/controller/profiili/YksiloController.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/YksiloDto.java
src/main/java/fi/okm/jod/yksilo/dto/profiili/export/YksiloExportDto.java
src/main/java/fi/okm/jod/yksilo/entity/Yksilo.java
src/main/java/fi/okm/jod/yksilo/service/profiili/ExportMapper.java
src/main/java/fi/okm/jod/yksilo/service/profiili/YksiloService.java
src/main/resources/db/migration/V20250915.2057__remove_lupa_arkistoida_column.sql
src/test/java/fi/okm/jod/yksilo/controller/profiili/YksiloControllerTest.java
src/test/java/fi/okm/jod/yksilo/service/profiili/YksiloServiceTest.java

Poistettu käyttämätön lupaArkistoida-kenttä.
https://jira.eduuni.fi/browse/OPHJOD-2057

Ophjod 2057
